spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rgt
    username: will
    password: '0000'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: validate

oauth2:
  google:
    client-id:
    client-secret:
    redirect-uri: http://localhost:8080/api/auth/google
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
